GoPickYourself/WSDLLC.Events.WebApp/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WSDLLC.Events.BusinessLogic;
using WSDLLC.Events.Core.Contracts;
using WSDLLC.Events.Domain.Models;
using WSDLLC.Events.WebApp.Helpers;

namespace WSDLLC.Events.WebApp.Controllers
{
    [SecureContextHeader]
    [AuthorizationNeededHeader]
    public class ManagementController : Controller
    {
        private readonly IAppBusinessLogic _logic;
        public ManagementController()
        {
            _logic = new AppBusinessLogic(ConfigurationManager.ConnectionStrings["ConnString"].ConnectionString);
        }
        [HttpGet]
        public ActionResult AnouncementManagement()
        {
            return
                View();
        }
        [HttpPost]
        public ActionResult SearchAnouncements(AnouncementSearch search)
        {
            search.PageSize = int.MaxValue;
            search.PageIndex = 0;
            return
                View(_logic.SearchAnouncement(search));
        }
        // GET: Management
        public ActionResult ManagementPanel()
        {
            return View();
        }
        [HttpGet]
        public ActionResult EditAnouncement(int id)
        {
            return
                View(_logic.SearchAnouncement(new AnouncementSearch
                {
                    Id = id,
                    PageSize = 1
                }).Single());
        }
        [HttpPost]
        public ActionResult EditAnouncement(AnouncementModel anouncement)
        {
            try
            {
                _logic.AddOrUpdateAnouncement(anouncement);
                return
                    RedirectToAction("AnouncementManagement");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return
                    View(anouncement);
            }
        }
        [HttpGet]
        public ActionResult AddAnouncement()
        {
            return
                View();
        }
        [HttpPost]
        public ActionResult AddAnouncement(AnouncementModel anouncement)
        {
            try
            {
                _logic.AddOrUpdateAnouncement(anouncement);
                return
                    RedirectToAction("AnouncementManagement");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return
                    View(anouncement);
            }
        }
        [HttpGet]
        public ActionResult CreateUser()
        {
            return
                View();
        }
        [HttpPost]
        public ActionResult CreateUser(UserModel user, int userLevel)
        {
            try
            {
                user.UserLevel = (UserLevelModel)userLevel;
                _logic.RegisterOrUpdateUser(user);
                return
                    RedirectToAction("Users");
            }
            catch (Exception ex)
            {
                return
                    View(user);
            }
        }
        [HttpGet]
        public ActionResult EditUser(long id)
        {
            long total;
            return
                View(_logic.SearchUsers(new UserSearchModel
                {
                    PageSize = 1,
                    UserId = id
                }, out total).Single());
        }
        [HttpPost]
        public ActionResult EditUser(UserModel user, int userLevel)
        {
            try
            {
                user.UserLevel = (UserLevelModel)userLevel;
                _logic.RegisterOrUpdateUser(user);
                return
                    RedirectToAction("Users");
            }
            catch (Exception ex)
            {
                ViewBag.FriendlyError = "Unable To Update User";
                return
                    View(user);
            }
        }
        [HttpGet]
        public ActionResult Users()
        {
            long total;
            var s = _logic.SearchUsers(new UserSearchModel
            {
                PageSize = 100
            }, out total);
            ViewBag.Total = total;
            return
                View(s);
        }
    }
}

GoPickYourself/WSDLLC.Events.WebApp/Views/Management/AddAnouncement.cshtml
@model WSDLLC.Events.Domain.Models.AnouncementModel

@{
    ViewBag.Title = "AddAnouncement";
}

<h2>Add Anouncement</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Anouncement" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Anoucements", "AnouncementManagement")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GoPickYourself/WSDLLC.Events.WebApp/Views/Management/AnouncementManagement.cshtml
@model WSDLLC.Events.Domain.Models.AnouncementSearch

@{
    ViewBag.Title = "AnouncementManagement";
}

<h2>Anouncement Management</h2>

@Html.ActionLink("Create Anouncement","AddAnouncement","Management")

@using (Html.BeginForm("SearchAnouncements","Management")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Anouncement Search</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CurrentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.CurrentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GoPickYourself/WSDLLC.Events.WebApp/Views/Management/CreateUser.cshtml
@model WSDLLC.Events.Domain.Models.UserModel

@{
    ViewBag.Title = "Create User";
}

<h2>Create User</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NickName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NickName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NickName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            User Level
            <div class="col-md-10">
                <select id="userLevel" name="userLevel">
                    <option value="0">SUPER ADMIN</option>
                    <option value="1">ADMIN</option>
                    <option value="2">MODERATOR</option>
                    <option value="3">USER</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="addbutton btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GoPickYourself/WSDLLC.Events.WebApp/Views/Management/EditAnouncement.cshtml
@model WSDLLC.Events.Domain.Models.AnouncementModel

@{
    ViewBag.Title = "Edit Anouncement";
}

<h2>Edit Anouncement</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @Html.HiddenFor(x => x.AnouncementId)

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AnouncementManagement")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GoPickYourself/WSDLLC.Events.WebApp/Views/Management/EditUser.cshtml
@model WSDLLC.Events.Domain.Models.UserModel

@{
    ViewBag.Title = "Edit User";
}

<script type="text/javascript">
    $(document).ready(function () {
        @{ 
                var p = (int)Model.UserLevel;
            }
            $('#userLevel').val('@p');
        $('#txtPin').val('');
        $('#txtUsername').val('');
        $('#txtEmail').val('');
        $('#txtPhone').val('');
    });
</script>

<h2>Edit User</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @Html.HiddenFor(x => x.UserId)
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", id="txtUsername" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pin, new { htmlAttributes = new { @class = "form-control", id="txtPin" } })
                @Html.ValidationMessageFor(model => model.Pin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id="txtEmail" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NickName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NickName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NickName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", id="txtPhone" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="userLevel">User Level</label>
            <div class="col-md-10">
                <select id="userLevel" name="userLevel">
                    <option value="0">SUPER ADMIN</option>
                    <option value="1">ADMIN</option>
                    <option value="2">MODERATOR</option>
                    <option value="3">USER</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="savebutton btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Users", "Users")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GoPickYourself/WSDLLC.Events.WebApp/Views/Management/ManagementPanel.cshtml
@{
    ViewBag.Title = "Management Panel";
}

<h2>Management Panel</h2>
<div>
    @Html.ActionLink("Admin Users","Users","Management")
    <br/>
    @Html.ActionLink("Admin Anouncements","AnouncementManagement","Management")
</div>

GoPickYourself/WSDLLC.Events.WebApp/Views/Management/SearchAnouncements.cshtml
@model IEnumerable<WSDLLC.Events.Domain.Models.AnouncementModel>

@{
    ViewBag.Title = "SearchAnouncements";
}

<h2>Search Anouncements</h2>

<p>
    @Html.ActionLink("Create New Anouncement", "AddAnouncement")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AnouncementId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AnouncementId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditAnouncement", new { id=item.AnouncementId }) |       
            @Html.ActionLink("Delete", "DeleteAnouncement", new { id=item.AnouncementId })
        </td>
    </tr>
}

</table>

GoPickYourself/WSDLLC.Events.WebApp/Views/Management/Users.cshtml
@model IEnumerable<WSDLLC.Events.Domain.Models.UserModel>

@{
    ViewBag.Title = "Users";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#txtEventId').autocomplete({
            source: '/EventApp/EventAutoComplete'
        });
        $('#btnSearch').click(function () {
            var guid = $('#txtEventId').val().split(":", 2);
            if (guid.length <= 1)
            {
                guid = null;
            }
            var index = 0;
            if ($('#pageIndex').val() != '')
            {
                index = parseInt($('#pageIndex').val())-1;
            }
            $.ajax({
                url: '/EventApp/GetUsers',
                method: 'POST',
                data: {
                    lastname: $('#txtLastName').val(),
                    eventId: guid,
                    firstName: $('#txtFirstName').val(),
                    nickname: $('#txtNickName').val(),
                    pageIndex: index
                },
                success : function(data)
                {
                    if(data.Success)
                    {
                        $('#resultsBody').html('');
                        for(var i in data.Data)
                        {
                            var item = data.Data[i];
                            
                            var res = $('#resultsBody');
                            res.append("<tr>");
                            res.append("<td> "+item.UserId +"</td>");
                            res.append("<td>" + item.Username + "</td>");
                            res.append("<td>" + item.FirstName + "</td>");
                            res.append("<td>" + item.LastName + "</td>");
                            res.append("<td>" + item.Email + "</td>");
                            res.append("<td>" + item.NickName + "</td>");
                            res.append("<td>" + item.PhoneNumber + "</td>");
                            res.append("<td>" + item.Username + "</td>");
                            res.append("<td><a href='/EventApp/EditUser?id=" +item.UserId  + "'>Edit User</a></td></tr>" );
                        }
                        $('#pageIndex').html('');
                        for(var l =1; l <= data.Total; l++)
                        {
                            $('#pageIndex').append('<option value="' + l + "'>" + l + "</option>");
                        }
                    }
                }
            });
        });
    });
</script>

<h2>Users</h2>

<p>
    @Html.ActionLink("Create New User", "CreateUser")
</p>
<div id="controls">
    Search By:
    <table class="table">
    <tbody>  
          <tr><td>
     Event Name:</td><td> <input type="text" id="txtEventId" class="form-control" /></td></tr>
        <tr><td>Last Name</td><td><input type="text" id="txtLastName" class="form-control" /></td></tr>
    <tr><td>First Name</td><td><input type="text" id="txtFirstName"/></td></tr>
        <tr><td>Nick Name</td><td><input type="text" id="txtNickName"/></td></tr>
        <tr><td>Page </td><td><select id="pageIndex">
                @for(int i = 1; i <= ViewBag.Total;i++)
                {
                    <option value="@i">@i</option>
                }
            </select></td></tr>
        <tr><td colspan="2"><input type="button" id="btnSearch" class="btn btn-default" value="Search"/></td></tr>    
    </tbody>
    </table>
    
</div>
<table class="table filtertable sorttable">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NickName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th></th>
    </tr>
        </thead>
    <tbody id="resultsBody">
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NickName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
     
        <td>
            @Html.ActionLink("Edit User", "EditUser", new { id=item.UserId }) 
          
        </td>
    </tr>
}
        </tbody>
</table>