GoPickYourself/WSDLLC.Events.WebApp/Controllers/EventAppController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WSDLLC.Events.BusinessLogic;
using WSDLLC.Events.Core.Contracts;
using WSDLLC.Events.Domain.Models;
using WSDLLC.Events.WebApp.Helpers;

namespace WSDLLC.Events.WebApp.Controllers
{
    [SecureContextHeader]
    [AuthorizationNeededHeader]
    public class EventAppController : Controller
    {
        private readonly IAppBusinessLogic _logic;
        public EventAppController()
        {
            _logic = new AppBusinessLogic(ConfigurationManager.ConnectionStrings["ConnString"].ConnectionString);
        }
        public ActionResult Chat()
        {
            return View();
        }
        
        // GET: EventApp
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult CreateEvent()
        {
            return
                View();
        }
        [HttpGet]
        public ActionResult MyEvents()
        {
            return
                View(_logic.EventSearch(new EventSearchModel
                {
                    PageSize = int.MaxValue,
                    UserId = ((UserModel)Session["User"]).UserId
                }));
        }
       
        [HttpGet]
        public ActionResult EditEvent(Guid id)
        {
            return
                View(_logic.EventSearch(new EventSearchModel
                {
                    EventId = id,
                    UserId = (((UserModel)Session["User"]).UserId),
                    PageSize = 1
                }).Single());
        }
        [HttpGet]
        public ActionResult DetailsEvent(Guid id)
        {
            return
                View(_logic.EventSearch(new EventSearchModel
                {
                    EventId = id,
                    PageSize = 1
                }).Single());
        }
        [HttpGet]
        public ActionResult ImageEdit(Guid id)
        {
            return
                View(_logic.SearchImages(new ImageSearchModel
                {
                    PageSize = 1,
                    UserId = ((UserModel)Session["User"]).UserId,
                    ImageId = id
                }).Single());
        }
        [HttpGet]
        public ActionResult ImageDetails(Guid id)
        {
            return
                View(_logic.SearchImages(new ImageSearchModel
                {
                    PageSize = 1,
                    ImageId = id
                }).Single());
        }
        [HttpPost]
        public ActionResult AddCoordinatorToEvent(int userId, Guid eventId)
        {
            try
            {
                var ev = _logic.EventSearch(new EventSearchModel
                {
                    EventId = eventId,
                    PageSize = 1
                }).Single();
                if (ev.Coordinators == null)
                {
                    ev.Coordinators = new List<UserModel>();
                }
                long t;
                ev.Coordinators.Add(_logic.SearchUsers(new UserSearchModel
                {
                    UserId = userId,
                    PageSize = 1
                }, out t).Single());
                _logic.AddOrUpdateEvent(ev, ConfigurationManager.AppSettings["GoogleMapsApiKey"]);
                return
                    Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return
                    Json(new { Success = false, FriendlyError = "Unable To Add Coordinator" }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult SearchEvents(EventSearchModel search)
        {
            search.PageSize = 1000;
            if (string.IsNullOrEmpty(search.Code))
            {
                search.Code = "Public";
            }
            return
                View(_logic.EventSearch(search));
        }
        [HttpGet]
        public ActionResult EventAutoComplete(string term)
        {
            var s = _logic.EventSearch(new EventSearchModel
            {
                PageSize = 100,
                EventName = term
            }).Select(x => new { label = x.Name, value = x.EventId }).ToArray();
            return
                Json(
                   s
                , JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult UserAutocomplete(string term)
        {
            long total;
            var s = _logic.SearchUsers(new UserSearchModel
            {
                PageSize = 20,
                NickName = term
            }, out total).Select(z => (z.LastName + ", " + z.FirstName + "("+(z.NickName??"")+")").Replace(":","") + ":" + z.UserId).ToArray();
            s.Union(_logic.SearchUsers(new UserSearchModel
            {
                PageSize = 20,
                LastName = term
            }, out total).Select(z => (z.LastName + ", " + z.FirstName + "(" + (z.NickName ?? "") + ")").Replace(":", "") + ":" + z.UserId).ToArray());
            return
                Json(
                    s
                , JsonRequestBehavior.AllowGet);
        }
      
        [HttpPost]
        [HttpGet]
        public ActionResult GetUsers(Guid? eventId, string lastname, string firstname, string nickname, string username, int pageIndex)
        {
            long total;
            var s = _logic.SearchUsers(new UserSearchModel
            {
                PageSize = 100,
                PageIndex = pageIndex,
                LastName = lastname,
                FirstName = lastname,
                EventId = eventId,
                NickName = nickname
            }, out total);
            ViewBag.Total = total;
            return
                View(s);
        }
      
        [HttpPost]
        public ActionResult RemoveTagFromImage(string tagName, Guid imageId)
        {
            try
            {
                _logic.RemoveTagFromImage(imageId, tagName);
                return
                    Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return
                    Json(new { Success = false, Error = ex.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult ImageEdit(ImageModel img, string hashTags)
        {
            try
            {
                img.ImageId = Guid.Empty;
                if (Request.Files.Count > 0)
                {
                    var reader = new BinaryReader(Request.Files[0].InputStream);
                    byte[] bits = new byte[Request.Files[0].ContentLength];
                    reader.Read(bits, 0, bits.Length);
                    img.Picture = bits;
                }
                if (hashTags != null && hashTags.Trim() != string.Empty)
                {
                    img.Tags = hashTags.Split('#').Select(x => new TagModel
                    {
                        TagName = x.Trim()
                    }).ToList();
                }
               
                img.ImageId = _logic.AddOrUpdateImage(img, System.IO.File.ReadAllBytes(Server.MapPath("~/Content/GoPickYourselfLogo25.png")));
                _logic.AddImageToUser(img, ((UserModel)Session["User"]));
                return
                    RedirectToAction("SharedPictures");
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Error Updating Image";
                return
                    View(img);
            }
        }
        [HttpPost]
        public ActionResult EditEvent(SharedEventModel eventModel, string hashTags, int EventType)
        {
            return
                UpdateEvent(eventModel, hashTags, EventType);
            //try
            //{
            //    var user = Session["User"] as UserModel;
            //    eventModel.Coordinators = new List<UserModel>();
            //    eventModel.Coordinators.Add(user);
            //    eventModel.EventType = (EventTypeModel)EventType;
            //    if(string.IsNullOrEmpty(eventModel.Code ))
            //    {
            //        eventModel.Code = "Public";
            //    }
            //    if (eventModel.Tags == null)
            //    {
            //        eventModel.Tags = new List<TagModel>();
            //    }
            //    if (!string.IsNullOrEmpty(hashTags))
            //    {
            //        eventModel.Tags.AddRange(CreateTags(hashTags));
            //    }
            //    if(eventModel.Images == null)
            //    {
            //        eventModel.Images = new List<ImageModel>();
            //    }
            //    var list = GetImagesFromFiles(eventModel);
            //    if (list != null)
            //    {
            //        eventModel.Images.AddRange(list);
            //    }
            //    if (eventModel.Images == null)
            //    {
            //        eventModel.Images = new List<ImageModel>();
            //    }
            //    var curCamImg = "cameraupload_";
            //    var index = Request.Form.AllKeys.Where(x => x.Contains(curCamImg));

            //    foreach(var key in index)
            //    {                   
            //        var base64 = Request[key];
            //        if (string.IsNullOrEmpty(base64))
            //        {
            //            continue;
            //        }
            //        base64 = base64.Substring(base64.IndexOf("base64," + 7));
            //        var img = Convert.FromBase64String(base64);
            //        eventModel.Images.Add(new ImageModel
            //        {
            //            Code = Request["Code"] ?? "Public",
            //            IsProfilePicture = false,
            //            Tags = eventModel.Tags,

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/AddImage.cshtml
@model WSDLLC.Events.Domain.Models.ImageModel

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript" src="~/Scripts/Common.js"></script>
<script type="text/javascript" src="~/Scripts/ImageApi.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnSaveImage').click(function () {
            if ($('#picLibUpload').val() != '') {
                ReadDataURL('imgCanvas', 0);
            }
            else if($('cameraUpload').val() != '')
            {
                ReadDataURL('imgCanvas', 1);
            }
            var dataUrl = toReadDataUrl('imgCanvas');
            var eventId = getURLParameter('eventId');
            var ispro = $('isprofilepic').is(':checked');
            AjaxUploadOfImage(eventId, dataUrl, ispro);
        });
        var eid = getURLParameter('eventId');
        if(!eid)
        {
            $('#frmIsProfileContent').show();
        }
        else
        {
            $('#frmIsProfileContent').hide();
        }
    });
</script>
<form action="/EventApp/AddImage" enctype="multipart/form-data" method="post">
    @Html.AntiForgeryToken()
    <div>
        <input type="hidden" id="hfImage" name="hfImage" />
    </div>
    <div class="form-horizontal">
        <h4>New Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ImageId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" id="frmIsProfileContent">
            @Html.LabelFor(model => model.IsProfilePicture, htmlAttributes: new { @class = "control-label col-md-2 isprofilepic" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsProfilePicture, new { id = "isprofilepic" })
                    @Html.ValidationMessageFor(model => model.IsProfilePicture, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label">
                Picture
            </label>
            <div class="col-md-10">
                <canvas id="imgCanvas" width="320" height="280"></canvas>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label">
                Upload From Library
            </label>
            <div class="col-md-10">
                <input accept="images/*" id="picLibUpload" type="file" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label">
                Upload From Camera
            </label>
            <div class="col-md-10">
                <input id="cameraUpload" type="file" accept="image/*" capture="camera">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" id="btnSaveImage" class="savebutton btn btn-default" />
            </div>
        </div>
    </div>
    </form>

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/CreateEvent.cshtml
@model WSDLLC.Events.Domain.Models.SharedEventModel

@{
    ViewBag.Title = "CreateEvent";
}
<script type="text/javascript" src="~/Scripts/VideoConverterApi.js"></script>
<script type="text/javascript" src="~/Scripts/recordvideoapi.js"></script>
<script type="text/javascript" src="~/Scripts/ImageApi.js"></script>
<script type="text/javascript" >
    $(document).ready(function () {
        $('.eventenddate').hide();
        var b = getBrowser();
        if (b !== 'Firefox' && b !== "Edge" && b !== 'Chrome' ) {
            $('#fuCamera').hide();
            $('#captureControls').hide();
            $('#imgControlsContainers').hide();
        }
        if(b === "Safari" || b === "IOS" || b === "Android")
        {
            $('#uploadsSafari').show();
        }
        else
        {
            $('#uploadsSafari').hide();
        }
    });
</script>
<h2>Create Event</h2>


<form action="/EventApp/CreateEvent" enctype="multipart/form-data" method="post">
   
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Event Type</label>
            <div class="col-md-10">
                @Html.DropDownList("EventType", WSDLLC.Events.WebApp.Helpers.HtmlExtensions.EventTypesList(0))
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <label for="cbxenddate" class="control-label">Event Has Mutiple Days?</label>
            <input type="checkbox" class="form-control cbxeventenddate" id="cbxenddate" />
            <div class="eventenddate">
                <label for="EventEndDate" class="control-label">Event End Date</label>
                <input name="EventEndDate" id="EventEndDate" type="text" class="datetimepicker form-control" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
           <label class="control-label col-md-2">State Or Province</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateOrProvince, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateOrProvince, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Postal Code</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", placeholder="USA" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            <label class="control-label">#'s</label>
            <input type="text" class="form-control" id="hashTags" name="hashTags" placeholder="#EventTag"/>
        </div>
        <div id="imgControlsContainers">
            <a href="#" onclick="AddFileUploadLibrary();">Add Image From Library</a>
            <br/>
            <a href="#" id="fuCamera" onclick="AddFileUploadCamera('player');">Add Image From Camera</a>
        </div>
        <div id="captureControls">
            <video id="player" autoplay="autoplay" controls="controls" height="200" width="200">

            </video>
            <br/>
            <input type="button" value="Take Picture" id="btnCameraCapture" onclick="TakePicture('player', 'thumbnailContainer', 'preview');" />
            <br/>
            <input type="button" value="Turn Off Camera" id="btnStopRecording" onclick="StopRecordingImages('player');" />
            <br />
            <canvas id="preview" width="200" height="200" class="hidden" />
        </div>
        <div id="uploadsSafari">
            <a href="#" onclick="AddFileUploadCameraIOS('imgContainer');" >Add Upload File</a>
        </div>
        <div>
            <div>
                Images:
            </div>
            <div id="thumbnailContainer">

            </div>
        </div>
        <div id="imgContainer">

        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Event" class="addbutton btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to Events", "MyEvents")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/DetailsEvent.cshtml
@model WSDLLC.Events.Domain.Models.SharedEventModel

@{
    ViewBag.Title = "DetailsEvent";
}
<script type="text/javascript" src="~/Scripts/twitterapi.js"></script>
<h2>Event Details</h2>
<script type="text/javascript">
    $(document).ready(function () {
        $('#imagesSlider').unslider();
    });
</script>

<div>
    <hr />
    <dl class="dl-horizontal">
     
        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateOrProvince)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateOrProvince)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>
        @if (Model.Latitude != null & Model.Longitude != null)
        {
            <dt>
                Location Link:
            </dt>

            <dd>
                @Html.Raw(WSDLLC.Events.WebApp.Helpers.HtmlExtensions.GoogleMapIcon(Model.Latitude.Value, Model.Longitude.Value))
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        @if (Model.Images != null)
            {
                <dt>
                    Images
                </dt>
                <dd>
                    <ul id="imagesSlider">
                    @foreach (var img in Model.Images)
                    {
                        <li>
                            <div><a href="/EventApp/ImageDetails?id=@img.ImageId">@Html.Raw(WSDLLC.Events.WebApp.Helpers.HtmlExtensions.ImageControlFromBytes(img.Picture, "Image", "Image"))</a></div>
                        </li>
                    }
                        </ul>
                </dd>
            }
        @if (Model.Coordinators != null)
        {
            <dt>
                Coordinators
            </dt>
            <dd>
                @foreach(var c in Model.Coordinators)
                {
                    <div>(@c.NickName) @c.FirstName @c.LastName</div>
                }
            </dd>
        }
        @if(Model.Tags != null)
        {
            <dt>
                #'s
            </dt>
            <dd>
                @for(var i =0; i < Model.Tags.Count; i++)
                {
                    @Model.Tags[i].TagName
                    if(i < Model.Tags.Count-1)
                    {
                        <span>,</span>
                    }
                }
            </dd>
        }
    </dl>
</div>
<div id="twittercontainer">

</div>
<div>
    <a class="tumblr-share-button" data-color="white" data-notes="right" href="https://embed.tumblr.com/share"></a>
    <script>!function(d,s,id){var js,ajs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://assets.tumblr.com/share-button.js";ajs.parentNode.insertBefore(js,ajs);}}(document, "script", "tumblr-js");</script>
</div>
<input type="hidden" id="hfId" value="@Model.EventId" />
<p>
    @if(Model.Coordinators != null && Model.Coordinators.Any(x => x.UserId == ((WSDLLC.Events.Domain.Models.UserModel) Session["User"]).UserId))
    {
        @Html.ActionLink("Edit Event", "EditEvent", new { id=Model.EventId }) 
    }
    @Html.ActionLink("Back to My Events", "MyEvents")
</p>

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/EventSearch.cshtml
@using (Html.BeginForm("SearchEvents","EventApp")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event Search</h4>
         
        <table class="table">
            <tr><td>Event Start Date</td><td><input type="text" name="EventDateStart" class="datepicker form-control"/></td></tr>
            <tr><td>Event End Date</td><td><input type="text" name="EventDateEnd" class="datepicker form-control" /></td></tr>
            <tr><td>City</td><td><input type="text" name="City" class="form-control" /></td></tr>
            <tr><td>Event Name</td><td><input type="text" name="EventName" class="form-control" /></td></tr>
            <tr><td>Description</td><td><input type="text" name="Description" class="form-control" /></td></tr>
            <tr><td>Code</td><td><input type="text" name="Code" class="form-control"/></td></tr>
            <tr><td colspan="2"><input type="submit" value="" class="searchbutton" width="100" height="100" /></td></tr>
        </table>
        
    </div>
}

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/FacebookImport.cshtml
@{
    ViewBag.Title = "Facebook Import";
}
<script type="text/javascript" src="~/Scripts/facebookapi.js"></script>
<script type="text/javascript" src="~/Scripts/instafeed.min.js"></script>
<script type="text/javascript" src="~/Scripts/instagramapi.js"></script>
<script type="text/javascript">
    function GoogleMyId()
    {
        var q = $('#txtUsername').val();
        window.open("https://smashballoon.com/instagram-feed/find-instagram-user-id/?username=" + q);
    }
    $(document).ready(function () {
        $('#loader').hide();
    });
</script>
<h2>Facebook and Instagram Import</h2>
<div>
    <img id="loader" src="~/Content/ajax-loader.gif" alt="loader" />
</div>
<div>
    <input class="form-control" type="button" id="btnFacebookImport" value="Import Pictures From Facebook"/>
</div>

<div>
    
    <label class="control-label">Instagram UserId (This is not your user name)</label>
    <br/>
    <input type="text" id="txtUserId" />
    <br />
    <input type="button" class="form-control" value="Import Instagram Photos" id="btnImportInstagram"/>
</div>
<div>
    <label class="control-label">My Username </label>
    <br />
    <input type="text" id="txtUsername"/>
    <br/>
    <input type="button" class="form-control" value="I don't know my User Id" onclick="GoogleMyId();" />
</div>

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/ImageSearch.cshtml
<h2>Image Search</h2>
<div>
    @using (Html.BeginForm("SearchImages", "EventApp"))
    {
        <table class="table">
            <tbody>
                <tr>
                    <td>Hash Tags</td><td><input type="text" id="hashtags" name="hashtags" class="form-control"/></td>
                </tr>
                <tr>
                    <td>Image Code</td>
                    <td><input type="text" id="imagecode" name="imagecode" class="form-control" /></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input class="searchbutton" type="submit" value="" />
                    </td>
                </tr>
            </tbody>
        </table>
    }
</div>

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/Search.cshtml
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

@Html.Partial("~/Views/EventApp/EventSearch.cshtml")

@Html.Partial("~/Views/EventApp/ImageSearch.cshtml")


<div>
    @Html.ActionLink("Back","Dashboard","EventApp")
</div>

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/SearchImages.cshtml
@model IEnumerable<WSDLLC.Events.Domain.Models.ImageModel>

@{
    ViewBag.Title = "Search Images";
}
<script type="text/javascript">
    $(document).ready(function () {
        $('.variable').unslider({
            infinite: true
        });

    });
</script>
<h2>Image Search</h2>

<div class="variable slider">
    <ul>
        @foreach (var item in Model)
        {
            <li>

                <a href="/EventApp/ImageDetails?id=@item.ImageId">@Html.Raw(WSDLLC.Events.WebApp.Helpers.HtmlExtensions.ImageControlFromBytes(item.Picture, item.ImageId.ToString(), "Edit Image"))</a>

            </li>
        }
    </ul>
</div>
<div>
   @Html.ActionLink("Back", "Search", "EventApp")
</div>

GoPickYourself/WSDLLC.Events.WebApp/Views/EventApp/SharedPictures.cshtml
@model IEnumerable<WSDLLC.Events.Domain.Models.ImageModel>

@{
    ViewBag.Title = "Shared Pictures";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('.variable').unslider({
            infinite: true
        });
       
    });
</script>

<h2>Shared Pictures</h2>

<div class="variable slider">
    <ul>
    @foreach (var item in Model)
    {
        <li>
            
                <a href="/EventApp/ImageEdit?id=@item.ImageId">@Html.Raw(WSDLLC.Events.WebApp.Helpers.HtmlExtensions.ImageControlFromBytes(item.Picture, item.ImageId.ToString(), "Edit Image"))</a>
            
        </li>
    }
        </ul>
    </div>